server:
    port: 9090

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: QQpp1111
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: com.nukezam.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:

    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql